// §8.6 bench gates (ENFORCED from 0.7.0): disabled ≤1.05× debug · enabled-pretty ≥1.5× debug
// · ndjson ≥0.8× pino. Each suite runs in its OWN process — enable()/configure() are global
// state, and mitata defers execution to run(), so co-hosted suites would cross-contaminate.
// G-14 margin policy: every suite runs BENCH_RUNS (default 5) times and a gate passes only
// if the WORST run clears its threshold — single-shot numbers hid a multi-× run-to-run
// spread on the ndjson suite. Ratios are computed per run (both sides measured in the same
// child process) so machine-state drift cancels within a sample.
// BENCH_EXTRA_NODE=<path-to-node-binary> re-runs the full protocol on a second runtime
// (the §6 disabled gate is specced on 26.5.0 AND 24.18.0); its gates are enforced too.
// Writes RESULTS.md; exits non-zero on any breach. Run from repo root after a build.
import { execFileSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const RUNS = Number(process.env.BENCH_RUNS ?? 5)

const suiteOnce = (name, execPath) => {
  const path = fileURLToPath(new URL(`./suites/${name}.mjs`, import.meta.url))
  const out = execFileSync(execPath, [path], { encoding: 'utf8' })
  const line = out.split('\n').find((l) => l.startsWith('##JSON##'))
  if (!line) throw new Error(`${name}: no result marker in output:\n${out}`)
  const rows = JSON.parse(line.slice(8))
  return Object.fromEntries(rows.map((r) => [r.alias, r.avg]))
}

const median = (xs) => {
  const s = [...xs].sort((a, b) => a - b)
  const mid = s.length >> 1
  return s.length % 2 ? s[mid] : (s[mid - 1] + s[mid]) / 2
}

const baselineOf = (sample) => {
  const entry = Object.entries(sample).find(([alias]) => alias !== 'modern-debug')
  return entry ? { alias: entry[0], avg: entry[1] } : { alias: '?', avg: Number.NaN }
}

const GATES = [
  {
    suite: 'disabled',
    name: 'disabled: modern-debug ≤ 1.05× debug',
    ratio: (r) => r['modern-debug'] / r.debug,
    pass: (v) => v <= 1.05,
    worst: (xs) => Math.max(...xs),
    render: (v) => `${v.toFixed(3)}× debug (gate ≤1.05×)`,
  },
  {
    suite: 'pretty',
    name: 'enabled-pretty: modern-debug ≥ 1.5× debug throughput',
    ratio: (r) => r.debug / r['modern-debug'],
    pass: (v) => v >= 1.5,
    worst: (xs) => Math.min(...xs),
    render: (v) => `${v.toFixed(2)}× debug throughput (gate ≥1.5×)`,
  },
  {
    suite: 'ndjson',
    name: 'ndjson: modern-debug ≥ 0.8× pino throughput',
    ratio: (r) => r.pino / r['modern-debug'],
    pass: (v) => v >= 0.8,
    worst: (xs) => Math.min(...xs),
    render: (v) => `${v.toFixed(2)}× pino throughput (gate ≥0.8×)`,
  },
]

const runtime = (execPath, label) => {
  const version = execFileSync(execPath, ['--version'], { encoding: 'utf8' }).trim()
  console.log(`== ${label}: node ${version}, ${RUNS} runs/suite ==`)
  const rows = []
  let failed = 0
  for (const g of GATES) {
    const samples = Array.from({ length: RUNS }, () => suiteOnce(g.suite, execPath))
    const ratios = samples.map(g.ratio)
    const worst = g.worst(ratios)
    const ok = g.pass(worst)
    if (!ok) failed++
    rows.push({
      g,
      ratios,
      worst,
      ok,
      oursMedian: median(samples.map((s) => s['modern-debug'])),
      base: baselineOf(samples[0]).alias,
      baseMedian: median(samples.map((s) => baselineOf(s).avg)),
    })
    console.log(
      `${ok ? 'PASS' : 'FAIL'}: ${g.name} -> worst ${g.render(worst)} | ` +
        `min ${Math.min(...ratios).toFixed(3)} / med ${median(ratios).toFixed(3)} / max ${Math.max(...ratios).toFixed(3)}`,
    )
  }
  return { version, rows, failed }
}

const results = [runtime(process.execPath, 'primary')]
if (process.env.BENCH_EXTRA_NODE) {
  results.push(runtime(process.env.BENCH_EXTRA_NODE, 'extra'))
}

const fmt = (n) => `${n.toFixed(1)} ns`
const lines = [
  '# bench/RESULTS.md',
  '',
  `Generated by \`node bench/run-benches.mjs\` on ${process.platform}-${process.arch}.`,
  `mitata 1.0.34 averages; each suite isolated in its own process; N=${RUNS} runs per suite.`,
  '',
  'Margin policy (DECISIONS G-14): a gate passes only if the WORST of N runs clears its',
  'threshold; per-run ratios pair both sides inside one child process.',
  '',
  'Reproduce:',
  '',
  '```sh',
  'pnpm -C packages/modern-debug build',
  'node bench/run-benches.mjs                        # primary = current node',
  'BENCH_EXTRA_NODE=<path-to-node-24> node bench/run-benches.mjs   # + second runtime',
  '```',
]

for (const r of results) {
  lines.push(
    '',
    `## Node ${r.version}`,
    '',
    '| Suite | modern-debug (median) | baseline (median) |',
    '|---|---|---|',
  )
  for (const row of r.rows) {
    lines.push(`| ${row.g.suite} | ${fmt(row.oursMedian)} | ${row.base}: ${fmt(row.baseMedian)} |`)
  }
  lines.push('', '| Gate | Worst of N | min / median / max | Status |', '|---|---|---|---|')
  for (const row of r.rows) {
    lines.push(
      `| ${row.g.name} | ${row.g.render(row.worst)} | ` +
        `${Math.min(...row.ratios).toFixed(3)} / ${median(row.ratios).toFixed(3)} / ${Math.max(...row.ratios).toFixed(3)} | ` +
        `${row.ok ? 'PASS' : 'FAIL'} |`,
    )
  }
}

writeFileSync(new URL('./RESULTS.md', import.meta.url), `${lines.join('\n')}\n`)
process.exit(results.some((r) => r.failed > 0) ? 1 : 0)
